apiVersion: v1
kind: Service
metadata:
  name: {{ include "goLunch.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "goLunch.fullname" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083